from django.urls import path
from . import views

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('inscription/', views.inscription, name='inscription'),
    path('login/', views.connexion, name='connexion'),
    path('connexion/', views.connexion, name='ancien_connexion'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('creer-offre/', views.creer_offre, name='creer_offre'),
    path('offres/', views.liste_offres, name='liste_offres'),
    path('mes-offres/', views.mes_offres, name='mes_offres'),
    path('mes-candidatures/', views.mes_candidatures, name='mes_candidatures'),
    path('notifications/', views.mes_notifications, name='mes_notifications'),
    path('modifier-offre/<int:offre_id>/', views.modifier_offre, name='modifier_offre'),
    path('supprimer-offre/<int:offre_id>/', views.supprimer_offre, name='supprimer_offre'),
    path('postuler/<int:offre_id>/', views.postuler, name='postuler'),
    path('candidatures-recues/', views.candidatures_recues, name='candidatures_recues'),
    path('accepter/<int:candidature_id>/', views.accepter_candidature, name='accepter_candidature'),
    path('rejeter/<int:candidature_id>/', views.rejeter_candidature, name='rejeter_candidature'),
    path('planifier-entretien/<int:candidature_id>/', views.planifier_entretien, name='planifier_entretien'),
    path('modifier-entretien/<int:entretien_id>/', views.modifier_entretien, name='modifier_entretien'),
    path('messages/', views.messages_liste, name='messages_liste'),
    path('envoyer-message/', views.envoyer_message, name='envoyer_message'),
    path('conversation/<int:utilisateur_id>/', views.conversation, name='conversation'),
    path('profil/', views.mon_profil, name='mon_profil'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('alex-offre-ideale/', views.alex_offre_ideale, name='alex_offre_ideale'),
   path('alex-aide-offre/', views.alex_aide_offre, name='alex_aide_offre'),
   path('entretiens/', views.entretiens, name='entretiens'), 
path('blog/cv-conseils/', views.blog_cv_conseils, name='blog_cv_conseils'),
path('blog/preparer-entretien/', views.blog_preparer_entretien, name='blog_preparer_entretien'),
path('blog/tendances-2026/', views.blog_tendances_2026, name='blog_tendances_2026'),
path('export-statistiques/', views.export_statistiques, name='export_statistiques'),
path('generer-rapport/', views.generer_rapport_pdf, name='generer_rapport_pdf'),
path('supprimer-document/<int:doc_id>/', views.supprimer_document, name='supprimer_document'),
path('mes-documents/', views.mes_documents, name='mes_documents'),
# Export et rapports
path('export-statistiques/', views.export_statistiques, name='export_statistiques'),
path('generer-rapport-pdf/', views.generer_rapport_pdf, name='generer_rapport_pdf'),
]