# Generated by Django 6.0.4 on 2026-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0002_appstatushistory_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('recruteur', 'Recruteur'), ('admin', 'Administrateur')], default='candidat', max_length=20),
        ),
    ]
