# Generated by Django 6.0.4 on 2026-04-28 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='motDePasse',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appstatushistory',
            name='ancien_statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancien_statuts', to='candidature.statutcandidature'),
        ),
        migrations.AlterField(
            model_name='appstatushistory',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='candidature.candidature'),
        ),
        migrations.AlterField(
            model_name='appstatushistory',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appstatushistory',
            name='nouveau_statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouveau_statuts', to='candidature.statutcandidature'),
        ),
        migrations.AlterField(
            model_name='document',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidature.candidat'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Alerte'), ('error', 'Erreur')], default='info', max_length=20),
        ),
    ]
