# Generated by Django 6.0.4 on 2026-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0004_utilisateur_motdepasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], default='CDI', max_length=20),
        ),
    ]
