# Generated by Django 6.0.4 on 2026-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0005_offre_type_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
