# Generated by Django 6.0.4 on 2026-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0006_offre_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('cv', 'CV'), ('lettre_motivation', 'Lettre de motivation')], max_length=50),
        ),
    ]
