# Generated by Django 6.0.4 on 2026-05-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0007_alter_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
