# Generated by Django 6.0.4 on 2026-05-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0008_document_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
