# Generated by Django 6.0.4 on 2026-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0009_candidat_date_naissance_candidat_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='commentaire_recruteur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='note_evaluation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
