# Generated by Django 6.0.4 on 2026-05-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0010_candidature_commentaire_recruteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
