# Generated by Django 6.0.5 on 2026-05-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0011_candidature_lettre_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
